version: "3"
services:
  app:
    build: .
    image: "app:latest"
    ports:
      - "3000:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - .env

    redis:
      image: "redis:7.0-alpine"
      ports:
        - "6379:6379"
